[build]
  # Build command: unzip the dist.zip into site/leptos-bevy/dist directory
  command = "unzip -o site/leptos-bevy/dist.zip -d site/leptos-bevy/dist"
  
  # Publish directory: the dist directory where we unzip
  publish = "site/leptos-bevy/dist"
  
  # Functions directory (if you use Netlify Functions)
  # functions = "netlify/functions"

[build.environment]
  # Node.js version (if needed for any build tools)
  NODE_VERSION = "18"

# Redirect rules (backup, since we're copying _redirects to dist)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache WASM files
[[headers]]
  for = "/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
